### PR TITLE
Submission 454, Petitpierre/di Lenardo/Rappo

### PR DESCRIPTION
**Pull request by mtwente**
# Pull request

## Proposed changes

* add submission 454 (from https://github.com/RPetitpierre/digihistch24)

Co-authored-by: Rémi Petitpierre <38254995+RPetitpierre@users.noreply.github.com>
Co-authored-by: Isabella di Lenardo <isabella.dilenardo@epfl.ch>
Co-authored-by: Lucas Rappo <82209716+lucasrappo@users.noreply.github.com>

## Types of changes

- [x] New feature (non-breaking change which adds functionality).
- [ ] Enhancement (non-breaking change which enhances functionality)
- [ ] Bug Fix (non-breaking change which fixes an issue).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist

- [x] I have read the **[README](./README.md)** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have mentioned all co-authors in the PR description as `Co-authored-by: Name <email@domain.com>`.

## Summary by CodeRabbit

- **New Features**
  - Introduced a configuration file for a manuscript project using the Quarto framework, structuring content for academic publication.
  - Launched a comprehensive study on the automation of vectorization of historical cadastral plans, detailing methodology and findings.
  - Added a bibliography featuring key references in cadastral computing and historical data analysis.

- **Chores**
  - Created a `requirements.txt` file listing essential libraries for project dependencies, improving setup and environment management.

### CODE REVIEW

**Review by maehr — CHANGES_REQUESTED** [review]
@mtwente Thanks for adding submission 454. I am not sure whether the inline code is the best solution for our audience and for the later pdf compilation. We should discuss this tomorrow.

**Comment by maehr** [comment]
@RPetitpierre @lucasrappo Thank you very much for your submission. We decided to comment out your code section for the moment. Please provide us with the missing shape files in the `data` folder and link the code to the relevant sections in the text if possible (as for example in https://digihistch24.github.io/book-of-abstracts/submissions/462/). Please also add the programming language and code-fold instructions to your code blocks as shown below

```{python}
#| code-fold: true
import shapefile, tqdm, cv2, json
import numpy as np
import pandas as pd
...
```

We really appreciate that you provide code and we would love to render it on our platform as a superb example of portable code.

Best
Moritz

**Review by maehr — APPROVED** [review]

**Comment by RPetitpierre** [comment]
Dear Moritz @maehr,

Thank you for your message and sorry for the late reply. I was on holidays with no access to my email until Monday. I also found a minor but nasty bug in the code which took me a bit of time to fix.

The dynamic figure computation is not very adapted in this case, since the code takes a bit over an hour to run. Alternatively, I suggest to use a smaller data sample, which already greatly helps to understand the methodology and provides an exemplar result, covering just a neighborhood.

I updated the code according to your suggestions. I also updated the other data file (requirements, data, images) to match the generated sample result.

Don't hesitate to write me if you need anything else from my side, and thank you for all the work on organizing this conference, I am looking forward!

Best,

Remi

**Comment by maehr** [comment]
> Dear Moritz @maehr,
> 
> Thank you for your message and sorry for the late reply. I was on holidays with no access to my email until Monday. I also found a minor but nasty bug in the code which took me a bit of time to fix.
> 
> The dynamic figure computation is not very adapted in this case, since the code takes a bit over an hour to run. Alternatively, I suggest to use a smaller data sample, which already greatly helps to understand the methodology and provides an exemplar result, covering just a neighborhood.
> 
> I updated the code according to your suggestions. I also updated the other data file (requirements, data, images) to match the generated sample result.
> 
> Don't hesitate to write me if you need anything else from my side, and thank you for all the work on organizing this conference, I am looking forward!
> 
> Best,
> 
> Remi

Thank you very much. It doesn't matter if it takes long to run, we could try the whole data set. Quarto allows for freezing to safe compute. @mtwente Can you please take a look at the update?

**Pull request merged**
